services:
  db:
    image: postgres
    volumes:
      - $HOME/srv/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=password
    expose:
      - 5432:5432
    ports:
      - 5432:5432
    restart: always
  app:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=password
    expose:
      - 8080:8080
    ports:
      - 8080:8080
    depends_on:
      - db
  ui: 
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - app