version: '3'
services:
  database:
    image: postgres:latest
    container_name: database
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always


  backend:
    build: ./backend
    container_name: backend
    depends_on:
      - database
    environment:
      - DB_SERVER=database
    ports:
      - 8080:8080


  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - 3000:3000
    depends_on:
      - backend

  proxy:
    build: ./ProxyServer
    container_name: proxy
    ports:
      - 8000:8000
    depends_on:
      - frontend